apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  namespace: demo-app
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"