apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv-claim
  namespace: demo-app
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M