apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-pvc
  namespace: demo-app
  labels:
    app: nginx
    env: demo
spec:
  containers:
    - name: nginx
      image: nginx

      env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/app"
          name: demo-pv-storage
  volumes:
    - name: demo-pv-storage
      persistentVolumeClaim:
        claimName: demo-pv-claim

  