apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo-app
  labels:
    app: nginx
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: demo
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
