apiVersion: v1
kind: Pod
metadata:
  name: nginx-env-secret
  namespace: demo-app
  labels:
    app: nginx
    env: demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: DEMO_GREETING
          value: "Hello from the environment"
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
        - name: BACKED_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-vars
              key: backend-username
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-vars
              key: db-username
      ports:
        - containerPort: 80

  